service: ia-project-backend-node

provider:
  name: aws
  region: us-east-1
  runtime: nodejs16.x
  apiGateway:
    apiKeys:
      - value: authorizationKey
        description: API Gateway Authorization
    usagePlan:
      quota:
        limit: 5
        offset: 2
        period: MONTH
      throttle:
        burstLimit: 200
        rateLimit: 100
plugins:
  - serverless-webpack
  - serverless-offline

package:
  individually: true

custom:
  webpack:
    packager: npm
    excludeFiles: "**/*.test.ts"
  serverless-offline:
    httpPort: 8000
    reloadHandler: true

functions:
  recognitionRuntime:
    handler: src/handler.handler
    events:
      - http:
          method: POST
          path: /recognize
          private: true
          