export enum TESSERACT_CONSTANTS {
    TESSERACT_LANGUAGE = 'eng',
    TESSERACT_WHITELIST = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ',
    TESSERACT_PRESERVE_INTERWORD_SPACES = '0',
}

export enum STATUS_CODES {
    STATUS_NOT_FOUND = 404,
    STATUS_SUCCESS = 200,
    STATUS_SERVER_ERROR = 500,
}
